name: LastCommand
main: update.menexia.lastcommand.LastCommand
author: weasel5i2
previous author: weasel5i2
version: 1.53
commands:
  last:
    description: Repeats your last command
    usage: /last
    aliases: ["!", l, ".", "/"]
