name: LastCommand
main: net.weasel.LastCommand.LastCommand
author: weasel5i2
version: 1.41
commands:
  last:
    description: Repeats your last command
    usage: /last
  "!":
    description: Repeats your last command
    usage: "Usage: /!"
  l:
    description: Repeats your last command
    usage: "Usage: /l"
  ".":
    description: Repeats your last command
    usage: "Usage: /."
  "/":
    description: Repeats your last command
    usage: "Usage: //"
